### ISSUE TITLE
Feature Request: show seed pubkey

### ISSUE THREAD

**Issue by kornpow** [lightninglabs/lndinit#20]
It would be really great if this app could allow you to input an aezeed and respond with the node pubkey, as a way of checking a seed on an offline machine and matching to a node.

**Comment by guggero** [comment]
I think it would make sense to port some of the functionality of `chantools` over to `lndinit`. Some of those commands I only built into that tool because they weren't "worthy" of going into `lnd` directly. And since `lndinit` also kind of fits that role, that would make sense.
What do you think, @thinkmassive and @Roasbeef, should I port some of these commands over to `lndinit`?
 - [`dumpbackup`](https://github.com/guggero/chantools/blob/master/doc/chantools_dumpbackup.md) (dump/decrypt content of SCB file)
 - [`compactdb`](https://github.com/guggero/chantools/blob/master/doc/chantools_compactdb.md) (external/manual DB compaction)
 - [`derivekey --identity`](https://github.com/guggero/chantools/blob/master/doc/chantools_derivekey.md) (derive identity public key from seed to check seed backup integrity)
 - [`migratedb`](https://github.com/guggero/chantools/blob/master/doc/chantools_migratedb.md) (external/manual DB migration to latest version of lnd)

**Comment by thinkmassive** [comment]
Yes, these are all related to "LND initialization" and would be welcome additions to `lndinit` in my opinion.

**Comment by Roasbeef** [comment]
SGTM to add these. I guess one open question is if we start to add these features, what's the main line we'll want to draw in the sand between `chantools` and `lndinit`?

**Comment by guggero** [comment]
Good question. I would propose that everything that could be used during normal operations (in a production environment) should be in `lndinit`. And everything that's disaster recovery or edge case handling should remain in `chantools`.
